version: "3.7"

services:
  reverse-proxy:
    image: traefik:1.7-alpine
    restart: ${RESTART_MODE}
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.frontend.headers.isDevelopment=false
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSSeconds=31536000
      - traefik.frontend.auth.basic=${WEB_USER}:${WEB_PASS}
      - traefik.frontend.headers.customResponseHeaders=X-Powered-By:Ali Daghlani
      - traefik.enable=true
      - traefik.frontend.rule=Host:web.${OST_DOMAIN:-daghlani.ir}
      - traefik.port=8080
      - traefik.docker.network=http_network
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - http_network

  osTicket:
    container_name: osTicket
    restart: always
    hostname: osTicket
    image: ${OST_IMAGE:-daghlani/osTicket}:${OST_IMAGE_TAG:-latest}
    ports:
      - ${OST_PORT:-80}:80
    volumes:
      - ./osT_volumes/upload:/var/www/upload
      - ./osT_volumes/scripts:/var/www/scripts
    labels:
      #- traefik.frontend.headers.isDevelopment=false
      #- traefik.frontend.headers.forceSTSHeader=true
      #- traefik.frontend.headers.STSPreload=true
      #- traefik.frontend.headers.STSIncludeSubdomains=true
      #- traefik.frontend.headers.STSSeconds=31536000
      #- traefik.backend.loadbalancer.stickiness=true
      - traefik.frontend.headers.customResponseHeaders=X-Powered-By:Ali Daghlani
      - traefik.enable=true
      - traefik.frontend.rule=Host:support.${OST_DOMAIN:-daghlani.ir}
      - traefik.port=80
      - traefik.docker.network=http_network
    networks:
      ost_net:
      http_network:


  mysql:
    image: docker.raveshmand.ir/wordpress/mysql:5.7
    container_name: osT_mysql
    hostname: mysql.${OST_DOMAIN:-daghlani.ir}
    volumes:
      - ost_db:/var/lib/mysql
    ports:
      - 127.0.0.1:3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bKzXmyo7Ra4VertkdepnqQMiJ3aspo
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: bKzXmyo7Ra4VertkdepnqQMiJ3aspo
    networks:
      ost_net:

volumes:
  ost_db:

networks:
  ost_net:
  http_network:
    external: true
 
